name: Issue Closed Info

on:
  issues:
    types:
      - closed

jobs:
  print-issue-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run JavaScript code
      run: |
        const { issue } = require('@actions/github');

        async function main() {
          try {
            const issueData = await issue.get(context.issue);
            console.log('Issue Data:', JSON.stringify(issueData.data, null, 2));
          } catch (error) {
            console.error('Error:', error);
            process.exit(1);
          }
        }

        main();
