name: Print Issue Info on Closure

on:
  issues:
    types:
      - closed

jobs:
  print_issue_info:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Issue Information
        id: print-info
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Closed By: ${{ github.event.sender.login }}"
          echo "Closed At: ${{ github.event.issue.closed_at }}"
          echo "Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}"
          echo "Assignees: ${{ join(github.event.issue.assignees.*.login, ', ') }}"
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"  # Print the issue body

      - name: Save Issue Info as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: issue-info
          path: issue-info.txt
