name: Update Greeting

on:
  issues:
    types:
      - opened

jobs:
  update-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Private Repo
        run: |
          ls