name: Extract Issue Info

on:
  issues:
    types:
      - closed

jobs:
  extract-issue-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Clone target Repo
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN  }}
        run: |
          # Clone the target repository
          cd ..
          pwd
          echo ${TARGET_REPO_TOKEN}
          git clone https://Hao1Zhang1:${TARGET_REPO_TOKEN}@github.com/Hao1Zhang1/TEST_GITHUB_ACTION_FILE_STORING.git file_location_repo
          cd file_location_repo
      
      - name: Create JSON File
        run: |
          echo "$ISSUE_INFO" > issue_info.json

      - name: Commit JSON File
        run: |
          git config --global user.name "Hao1Zhang1"
          git config --global user.email "hao.zhang@jonesradiology.com.au"
          git add issue_info.json
          git commit -m "Add issue_info.json"
          git push

      - name: Push to Target Repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN  }}
        run: |
          # Commit and push to the target repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add issue_info.json
          git commit -m "Add issue_info.json from source repo"
          git push https://Hao1Zhang1:${TARGET_REPO_TOKEN}@github.com/Hao1Zhang1/TEST_GITHUB_ACTION_FILE_STORING.git

