name: Extract Issue Info
on:
  issues:
    types:
      - closed

jobs:
  extract-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install requests

      # - name: Extract Issue Info
      #   run: |
      #     python extract_issue_info.py
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create JSON File
        run: |
          echo "$ISSUE_INFO" > issue_info.json

      - name: Commit JSON File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add issue_info.json
          git commit -m "Add issue_info.json"
          git push

